[2024-11-12T00:37:41.057+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T00:37:41.100+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run_moving_average manual__2024-11-12T00:37:40.179645+00:00 [queued]>
[2024-11-12T00:37:41.111+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run_moving_average manual__2024-11-12T00:37:40.179645+00:00 [queued]>
[2024-11-12T00:37:41.112+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T00:37:41.126+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_moving_average> on 2024-11-12 00:37:40.179645+00:00
[2024-11-12T00:37:41.133+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run_moving_average', 'manual__2024-11-12T00:37:40.179645+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpiqcpa0xz']
[2024-11-12T00:37:41.136+0000] {standard_task_runner.py:91} INFO - Job 248: Subtask dbt_run_moving_average
[2024-11-12T00:37:41.138+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=388) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T00:37:41.139+0000] {standard_task_runner.py:63} INFO - Started process 389 to run task
[2024-11-12T00:37:41.201+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run_moving_average manual__2024-11-12T00:37:40.179645+00:00 [running]> on host a23c71b4588d
[2024-11-12T00:37:41.445+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run_moving_average' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T00:37:40.179645+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T00:37:40.179645+00:00'
[2024-11-12T00:37:41.446+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T00:37:41.488+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T00:37:41.490+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models moving_average --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-12T00:37:41.500+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T00:37:43.793+0000] {subprocess.py:93} INFO - [0m00:37:43  Running with dbt=1.8.8
[2024-11-12T00:37:44.967+0000] {subprocess.py:93} INFO - [0m00:37:44  Registered adapter: snowflake=1.8.4
[2024-11-12T00:37:45.212+0000] {subprocess.py:93} INFO - [0m00:37:45  Unable to do partial parsing because of a version mismatch
[2024-11-12T00:37:46.979+0000] {subprocess.py:93} INFO - [0m00:37:46  [[33mWARNING[0m]: Did not find matching node for patch with name 'session_summary' in the 'models' section of file 'models/schema.yml'
[2024-11-12T00:37:47.217+0000] {subprocess.py:93} INFO - [0m00:37:47  Encountered an error:
[2024-11-12T00:37:47.218+0000] {subprocess.py:93} INFO - Compilation Error
[2024-11-12T00:37:47.218+0000] {subprocess.py:93} INFO -   Model 'model.lab2_project.moving_average' (models/moving_average.sql) depends on a node named 'STOCK_PRICES' which was not found
[2024-11-12T00:37:48.403+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-12T00:37:48.404+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T00:37:48.414+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-12T00:37:48.419+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run_moving_average, run_id=manual__2024-11-12T00:37:40.179645+00:00, execution_date=20241112T003740, start_date=20241112T003741, end_date=20241112T003748
[2024-11-12T00:37:48.430+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 248 for task dbt_run_moving_average (Bash command failed. The command returned a non-zero exit code 2.; 389)
[2024-11-12T00:37:48.456+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T00:37:48.477+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T00:37:48.481+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
