[2024-11-12T00:07:15.648+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T00:07:15.682+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run_moving_average manual__2024-11-12T00:07:08.821197+00:00 [queued]>
[2024-11-12T00:07:15.694+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run_moving_average manual__2024-11-12T00:07:08.821197+00:00 [queued]>
[2024-11-12T00:07:15.695+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T00:07:15.713+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_moving_average> on 2024-11-12 00:07:08.821197+00:00
[2024-11-12T00:07:15.721+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=127) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-12T00:07:15.724+0000] {standard_task_runner.py:63} INFO - Started process 129 to run task
[2024-11-12T00:07:15.723+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run_moving_average', 'manual__2024-11-12T00:07:08.821197+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpstqtbzg8']
[2024-11-12T00:07:15.729+0000] {standard_task_runner.py:91} INFO - Job 241: Subtask dbt_run_moving_average
[2024-11-12T00:07:15.796+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run_moving_average manual__2024-11-12T00:07:08.821197+00:00 [running]> on host 8c774efb74b0
[2024-11-12T00:07:15.884+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run_moving_average' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T00:07:08.821197+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T00:07:08.821197+00:00'
[2024-11-12T00:07:15.886+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T00:07:15.887+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T00:07:15.888+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models moving_average --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-12T00:07:15.898+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T00:07:15.899+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /home/***/.local/bin/dbt: No such file or directory
[2024-11-12T00:07:15.899+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-11-12T00:07:15.903+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T00:07:15.913+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-11-12T00:07:15.918+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run_moving_average, run_id=manual__2024-11-12T00:07:08.821197+00:00, execution_date=20241112T000708, start_date=20241112T000715, end_date=20241112T000715
[2024-11-12T00:07:15.933+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 241 for task dbt_run_moving_average (Bash command failed. The command returned a non-zero exit code 127.; 129)
[2024-11-12T00:07:15.979+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T00:07:16.018+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T00:07:16.024+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
