[2024-11-11T23:40:24.358+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-11T23:40:24.396+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run_moving_average manual__2024-11-11T23:40:23.483718+00:00 [queued]>
[2024-11-11T23:40:24.404+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run_moving_average manual__2024-11-11T23:40:23.483718+00:00 [queued]>
[2024-11-11T23:40:24.405+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-11T23:40:24.418+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_moving_average> on 2024-11-11 23:40:23.483718+00:00
[2024-11-11T23:40:24.425+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run_moving_average', 'manual__2024-11-11T23:40:23.483718+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp2q3m05b3']
[2024-11-11T23:40:24.429+0000] {standard_task_runner.py:91} INFO - Job 234: Subtask dbt_run_moving_average
[2024-11-11T23:40:24.430+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=458) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-11T23:40:24.431+0000] {standard_task_runner.py:63} INFO - Started process 459 to run task
[2024-11-11T23:40:24.475+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run_moving_average manual__2024-11-11T23:40:23.483718+00:00 [running]> on host e49dd112e7cf
[2024-11-11T23:40:24.569+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run_moving_average' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T23:40:23.483718+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-11T23:40:23.483718+00:00'
[2024-11-11T23:40:24.570+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-11T23:40:24.587+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-11T23:40:24.588+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models moving_average --profiles-dir /opt/***/dags/build_test2 --project-dir /opt/***/dags/build_test2']
[2024-11-11T23:40:24.596+0000] {subprocess.py:86} INFO - Output:
[2024-11-11T23:40:27.119+0000] {subprocess.py:93} INFO - [0m23:40:27  Running with dbt=1.8.8
[2024-11-11T23:40:28.276+0000] {subprocess.py:93} INFO - [0m23:40:28  Registered adapter: snowflake=1.8.4
[2024-11-11T23:40:28.460+0000] {subprocess.py:93} INFO - [0m23:40:28  Unable to do partial parsing because of a version mismatch
[2024-11-11T23:40:30.145+0000] {subprocess.py:93} INFO - [0m23:40:30  [[33mWARNING[0m]: Did not find matching node for patch with name 'session_summary' in the 'models' section of file 'models/schema.yml'
[2024-11-11T23:40:30.361+0000] {subprocess.py:93} INFO - [0m23:40:30  Encountered an error:
[2024-11-11T23:40:30.361+0000] {subprocess.py:93} INFO - Compilation Error
[2024-11-11T23:40:30.362+0000] {subprocess.py:93} INFO -   Model 'model.build_test2.moving_average' (models/moving_average.sql) depends on a node named 'STOCK_PRICES' which was not found
[2024-11-11T23:40:31.108+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-11T23:40:31.109+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-11T23:40:31.119+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-11T23:40:31.123+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run_moving_average, run_id=manual__2024-11-11T23:40:23.483718+00:00, execution_date=20241111T234023, start_date=20241111T234024, end_date=20241111T234031
[2024-11-11T23:40:31.135+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 234 for task dbt_run_moving_average (Bash command failed. The command returned a non-zero exit code 2.; 459)
[2024-11-11T23:40:31.144+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-11T23:40:31.168+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-11T23:40:31.172+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
