[2024-11-11T03:42:10.724+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-11T03:42:10.817+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: two_stocks_DAG.extract_stock_data scheduled__2024-11-10T03:42:00+00:00 [queued]>
[2024-11-11T03:42:10.843+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: two_stocks_DAG.extract_stock_data scheduled__2024-11-10T03:42:00+00:00 [queued]>
[2024-11-11T03:42:10.846+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-11-11T03:42:10.908+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_stock_data> on 2024-11-10 03:42:00+00:00
[2024-11-11T03:42:10.934+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'two_stocks_DAG', 'extract_stock_data', 'scheduled__2024-11-10T03:42:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/two_stocks.py', '--cfg-path', '/tmp/tmpqw6o0t9v']
[2024-11-11T03:42:10.950+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask extract_stock_data
[2024-11-11T03:42:10.951+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=565) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-11T03:42:10.952+0000] {standard_task_runner.py:63} INFO - Started process 582 to run task
[2024-11-11T03:42:11.070+0000] {task_command.py:426} INFO - Running <TaskInstance: two_stocks_DAG.extract_stock_data scheduled__2024-11-10T03:42:00+00:00 [running]> on host e77131eeb98c
[2024-11-11T03:42:11.261+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='two_stocks_DAG' AIRFLOW_CTX_TASK_ID='extract_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T03:42:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-10T03:42:00+00:00'
[2024-11-11T03:42:11.277+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-11T03:42:11.321+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-11T03:42:11.325+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/two_stocks.py", line 21, in extract_stock_data
    api_key = Variable.get("vantage_api_key")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable vantage_api_key does not exist'
[2024-11-11T03:42:11.356+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=two_stocks_DAG, task_id=extract_stock_data, run_id=scheduled__2024-11-10T03:42:00+00:00, execution_date=20241110T034200, start_date=20241111T034210, end_date=20241111T034211
[2024-11-11T03:42:11.384+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 68 for task extract_stock_data ('Variable vantage_api_key does not exist'; 582)
[2024-11-11T03:42:11.429+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-11T03:42:11.477+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-11T03:42:11.480+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
