[2024-11-11T03:52:39.067+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-11T03:52:39.095+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: two_stocks_DAG.extract_stock_data manual__2024-11-11T03:47:35.416199+00:00 [queued]>
[2024-11-11T03:52:39.102+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: two_stocks_DAG.extract_stock_data manual__2024-11-11T03:47:35.416199+00:00 [queued]>
[2024-11-11T03:52:39.103+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-11-11T03:52:39.115+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_stock_data> on 2024-11-11 03:47:35.416199+00:00
[2024-11-11T03:52:39.122+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=939) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-11T03:52:39.124+0000] {standard_task_runner.py:63} INFO - Started process 942 to run task
[2024-11-11T03:52:39.122+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'two_stocks_DAG', 'extract_stock_data', 'manual__2024-11-11T03:47:35.416199+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/two_stocks.py', '--cfg-path', '/tmp/tmpyamlj8tv']
[2024-11-11T03:52:39.125+0000] {standard_task_runner.py:91} INFO - Job 101: Subtask extract_stock_data
[2024-11-11T03:52:39.167+0000] {task_command.py:426} INFO - Running <TaskInstance: two_stocks_DAG.extract_stock_data manual__2024-11-11T03:47:35.416199+00:00 [running]> on host e77131eeb98c
[2024-11-11T03:52:39.253+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='two_stocks_DAG' AIRFLOW_CTX_TASK_ID='extract_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T03:47:35.416199+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-11T03:47:35.416199+00:00'
[2024-11-11T03:52:39.255+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-11T03:52:39.266+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-11T03:52:39.267+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/two_stocks.py", line 21, in extract_stock_data
    api_key = Variable.get("vantage_api_key")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable vantage_api_key does not exist'
[2024-11-11T03:52:39.285+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=two_stocks_DAG, task_id=extract_stock_data, run_id=manual__2024-11-11T03:47:35.416199+00:00, execution_date=20241111T034735, start_date=20241111T035239, end_date=20241111T035239
[2024-11-11T03:52:39.331+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 101 for task extract_stock_data ('Variable vantage_api_key does not exist'; 942)
[2024-11-11T03:52:39.378+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-11T03:52:39.431+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-11T03:52:39.440+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
