[2024-11-11T23:32:23.427+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-11T23:32:23.467+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run_moving_average manual__2024-11-11T23:32:22.274993+00:00 [queued]>
[2024-11-11T23:32:23.479+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run_moving_average manual__2024-11-11T23:32:22.274993+00:00 [queued]>
[2024-11-11T23:32:23.479+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-11T23:32:23.495+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_moving_average> on 2024-11-11 23:32:22.274993+00:00
[2024-11-11T23:32:23.505+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run_moving_average', 'manual__2024-11-11T23:32:22.274993+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp41rdek21']
[2024-11-11T23:32:23.508+0000] {standard_task_runner.py:91} INFO - Job 232: Subtask dbt_run_moving_average
[2024-11-11T23:32:23.509+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=489) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-11T23:32:23.511+0000] {standard_task_runner.py:63} INFO - Started process 490 to run task
[2024-11-11T23:32:23.553+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run_moving_average manual__2024-11-11T23:32:22.274993+00:00 [running]> on host cb2183e9c38c
[2024-11-11T23:32:23.637+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run_moving_average' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T23:32:22.274993+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-11T23:32:22.274993+00:00'
[2024-11-11T23:32:23.638+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-11T23:32:23.653+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-11T23:32:23.654+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models moving_average --profiles-dir /opt/***/dags/build_test2 --project-dir /opt/***/dags/build_test2']
[2024-11-11T23:32:23.662+0000] {subprocess.py:86} INFO - Output:
[2024-11-11T23:32:25.931+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2024-11-11T23:32:25.932+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2024-11-11T23:32:25.933+0000] {subprocess.py:93} INFO - 
[2024-11-11T23:32:25.933+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/opt/***/dags/build_test2' does not exist.
[2024-11-11T23:32:26.094+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-11T23:32:26.095+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-11T23:32:26.106+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-11T23:32:26.110+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run_moving_average, run_id=manual__2024-11-11T23:32:22.274993+00:00, execution_date=20241111T233222, start_date=20241111T233223, end_date=20241111T233226
[2024-11-11T23:32:26.125+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 232 for task dbt_run_moving_average (Bash command failed. The command returned a non-zero exit code 2.; 490)
[2024-11-11T23:32:26.136+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-11T23:32:26.159+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-11T23:32:26.163+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
